services:
  nginx:
    build:
      context: .
      dockerfile: ./app/nginx/Dockerfile
    container_name: press-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  # No ports are exposed so we can use a private instance to check for broken
  # links. All scripts are executed within a container.
  nginx-test:
    build:
      context: .
      dockerfile: ./app/nginx/Dockerfile
    container_name: press-nginx-test

  nginx-dev:
    build:
      context: .
      dockerfile: ./app/nginx/Dockerfile
    container_name: press-nginx-dev
    ports:
      - "80:80"
    volumes:
      # Mount your HTML files. Adjust path to match how your config is set up.
      - ./build:/usr/share/nginx/html

      # Mount your custom NGINX config as /etc/nginx/conf.d/default.conf
      # - ../nginx/default.conf:/etc/nginx/conf.d/default.conf

      # If you're using certbot or any Let's Encrypt management inside/outside the container
      # - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  sync:
    build: ./app/s3
    container_name: press-sync
    entrypoint: ["/app/bin/sync"]
    environment:
      S3_BUCKET_PATH: ${S3_BUCKET_PATH:-s3://press}
      S3CFG_PATH: ${S3CFG_PATH:-/root/.s3cfg}
    volumes:
      - ../s3:/s3

  seed:
    build: ./app/s3
    container_name: press-seed
    entrypoint: ["/app/bin/seed"]
    environment:
      S3_BUCKET_PATH: ${S3_BUCKET_PATH:-s3://press}
      S3CFG_PATH: ${S3CFG_PATH:-/root/.s3cfg}
    volumes:
      - ../s3:/s3

  webp:
    build: ./app/webp
    container_name: press-webp
    entrypoint: ["/app/bin/service"]
    volumes:
      - ./app/webp/input:/app/input
      - ./app/webp/output:/app/output
      - ../log:/app/log

  # Default port is 6379. Not exposed to the host to avoid port conflicts.
  # You can run redis-cli within this container.
  #   docker compose exec dragonfly redis-cli
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    # Useful in avoiding conflicts from multiple active instances of press projects.
    container_name: press-dragonfly

  shell:
    image: press-shell
    build: ./app/shell
    container_name: press-shell
    entrypoint: ["bash"]
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      REDIS_HOST: dragonfly
      REDIS_PORT: 6379
      TEST_HOST_URL: ${TEST_HOST_URL:-https://nginx-test}
    volumes:
      - ./:/data
      - ./app/shell/mk:/app/mk
      - ./app/shell/bin:/app/bin
      - ./app/shell/py/pie/pie:/press/py/pie/pie
      - ./app/shell/py/pie/tests:/press/py/pie/tests
      - ./src/dep.mk:/app/mk/dep.mk

  release:
    image: press-release
    build:
      context: .
      dockerfile: ./app/release/Dockerfile

  pdoc:
    build: ./app/pdoc
    container_name: press-pdoc
    entrypoint: ["pdoc", "--http", "0.0.0.0:8080", "pie"]
    ports:
      - "8080:8080"
    volumes:
      - ./app/shell/py/pie:/pie
    profiles: ["pdoc"]
