services:
  nginx:
    build:
      context: .
      dockerfile: app/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  nginx-dev:
    build:
      context: .
      dockerfile: app/nginx/Dockerfile
    container_name: nginx-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount your HTML files. Adjust path to match how your config is set up.
      - ./build:/usr/share/nginx/html

      # Mount your custom NGINX config as /etc/nginx/conf.d/default.conf
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      # If you're using certbot or any Let's Encrypt management inside/outside the container
      # - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  sync:
    build: app/s3
    entrypoint: ["/app/bin/sync"]
    volumes:
      - ./s3:/s3

  seed:
    build: app/s3
    entrypoint: ["/app/bin/seed"]
    volumes:
      - ./s3:/s3

  service-framework:
    build: app/service-framework

  webp:
    build: app/webp
    entrypoint: ["/app/bin/service"]
    volumes:
      - ./app/webp/input:/app/input
      - ./app/webp/output:/app/output
      - ./log:/app/log

  shell:
    build: app/shell
    entrypoint: ["bash"]
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    volumes:
      - ./:/data
      - ./dep.mk:/app/mk/dep.mk
