from setuptools import setup, find_packages

setup(
    name="pie",
    version="0.1.0",
    packages=find_packages(),
    install_requires=["emoji", "markdown"],
    author="Brian Lee",
    author_email="",
    description="",
    url="",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
    entry_points={
        'console_scripts': [
            'check-author=pie.check.author:main',
            'check-breadcrumbs=pie.check.breadcrumbs:main',
            'check-canonical=pie.check.canonical:main',
            'check-page-title=pie.check.page_title:main',
            'check-post-build=pie.check.post_build:main',
            'check-sitemap-hostname=pie.check.sitemap_hostname:main',
            'check-unexpanded-jinja=pie.check.unexpanded_jinja:main',
            'check-underscores=pie.check.underscores:main',
            'check-all=pie.check.all:main',
            'create-post=pie.create.post:main',
            'create-site=pie.create.site:main',
            'emojify=pie.filter.emojify:main',
            'gen-markdown-index=pie.gen_markdown_index:main',
            'include-filter=pie.filter.include:main',
            'indextree-json=pie.indextree_json:main',
            'nginx-permalinks=pie.nginx_permalinks:main',
            'picasso=pie.build.picasso:main',
            'render-html=pie.render.html:main',
            'render-press=pie.render.press:main',
            'render-jinja-template=pie.render.jinja:main',
            'render-study-json=pie.render_study_json:main',
            'report-static-links=pie.report.static_links:main',
            'store-files=pie.store_files:main',
            'update-author=pie.update.author:main',
            'update-breadcrumbs=pie.update.breadcrumbs:main',
            'update-index=pie.update.index:main',
            'update-link-filters=pie.update.link_filters:main',
            'update-metadata=pie.update.metadata:main',
            'update-pubdate=pie.update.pubdate:main',
            'update-url=pie.update.url:main',
            'migrate-metadata=pie.update.migrate_metadata:main',
            'sitemap=pie.sitemap:main',
        ],
    },
)
